title: PeriodGoals
modelClass: Ebussola\ControlMyBudget\Models\PeriodGoal
list: $/ebussola/controlmybudget/models/periodgoal/columns.yaml
recordUrl: 'ebussola/controlmybudget/periodgoals/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
