list: $/ebussola/controlmybudget/models/purchase/columns.yaml
modelClass: Ebussola\ControlMyBudget\Models\Purchase
title: Purchases
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ebussola/controlmybudget/purchases/update/:id'
