list: $/ebussola/controlmybudget/models/purchasegroup/columns.yaml
modelClass: Ebussola\ControlMyBudget\Models\PurchaseGroup
title: PurchaseGroups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ebussola/controlmybudget/purchasegroups/update/:id'
