title: MonthlyGoals
modelClass: Ebussola\ControlMyBudget\Models\MonthlyGoal
list: $/ebussola/controlmybudget/models/monthlygoal/columns.yaml
recordUrl: 'ebussola/controlmybudget/monthlygoals/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
